### ISSUE TITLE
Write json Array lists to node values if there are multiple values

### ISSUE THREAD

**Issue by MartinWenge** [MartinWenge/neo4BFMPolymers#7]
Create (:Parameter {name:"MyBoxSize", value:[128,128,128]})
instead of 
Create (:Parameter {name:"MyBoxSize", value:"128 x 128 x 128"})

**Comment by Bondoki** [comment]
fixed in commit a0dac37deafdfaf5e9af7b6b082ace9ac5294034

**Comment by Bondoki** [comment]
Also reformat periodicity by conversion python "True" and "False" to JSON list with integer values 0 (false) and 1 (true). Should enhance compatibility with other languages other than Python (True, False) vs. JS (true and false)

**Comment by MartinWenge** [comment]
The specific format issue was fixed in a0dac37 and the booleans are corrected as well.
